### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by c-martinez** [sustainable-software-sustainability/website#23]
In #22, we are adding the first two of potentially many sections directly related to WoSSS21. It might be best if the wosss21 navigation item could be a drop down menu with different subsections (home, agenda, etc...)

I would imagine something like this:
![image](https://user-images.githubusercontent.com/7782231/111631506-bea1a780-87f3-11eb-92c6-8150d9a239f9.png)
 
@ctwhome -- do you know if that is possible?

**Comment by ctwhome** [comment]
it is possible. I can make it work next week on Wednesday. is that a good timing for you?

**Comment by c-martinez** [comment]
Sure, that would be great!
