### ISSUE TITLE
Stop animated cog

### ISSUE THREAD

**Issue by c-martinez** [sustainable-software-sustainability/website#44]
Request from a user:
Could the animated cog on the website be replaced with a static version, as it’s really distracting when trying to read pages (you could use the [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) CSS media query but I don’t know how many people who could benefit will be aware of how to change that setting so it might be simpler to remove the animation entirely).

**Comment by ctwhome** [comment]
What about making the move slower, but still with the motion?

**Comment by c-martinez** [comment]
I am not sure if that would work -- as I understand, people with ADHD could be easily distracted by the moving icon. Although I do like the animated version. With your experience in UX, what would be the best solution, that would both look nice & be accessible?

Do you think having the moving logo in the landing page, but use the static version on the header when you scroll down would be an option?

**Comment by ctwhome** [comment]
@c-martinez Thanks for the CSS suggestions. I agree every site should be as inclusive as we can. I added prefers-reduced motion to the animation (Apart from making it 2x slower). The animation will stop completely if the setting is enabled. 

![](https://user-images.githubusercontent.com/4195550/133588576-abf39853-a0fe-497f-945d-742276438655.png)
