### ISSUE TITLE
Setup a management email address e.g. info@wosss.org

### ISSUE THREAD

**Issue by shoaibsufi** [sustainable-software-sustainability/website#5]
we have the domain wosss.org but we don't have a way for people to contact the wosss team apart from individual email addresses.

It would be good to have an email address - e.g. info@wosss.org that forwarded to the the delivery team members at Netherlands eScience Center, DANS and SSI - e.g. Carlos, Peter/Gerard, Shoaib in the first instance

**Comment by c-martinez** [comment]
No support email - people can contact us via twitter or join slack - then see how this works and if it does not we can have a form for contacting us to stop spam
