### ISSUE TITLE
WoSSS logo

### ISSUE THREAD

**Issue by shoaibsufi** [sustainable-software-sustainability/website#7]
New logo to have binary of 2015 in - to denote when the workshop series started.

Carlos to liaise with the designer.

**Comment by ctwhome** [comment]
Please check branch [new-web](https://github.com/sustainable-software-sustainability/sustainable-software-sustainability.github.io/tree/new-web)

**Comment by c-martinez** [comment]
Logo looks great, closing this issue :-)
