### ISSUE TITLE
Generic component

### ISSUE THREAD

**Issue by c-martinez** [sustainable-software-sustainability/website#9]
Can we have 'generic' component which could easily include the content of a markdown file in the landing page?

**Comment by ctwhome** [comment]
We will have it the moment a small bug is fixed in the content module. It won't take long seeing previous responses from the Nuxt community. I have reported it here: https://github.com/nuxt/content/issues/360

**Comment by ctwhome** [comment]
A maybe better approach is to include Vue components inside `*.md` files in companion to HTML and the md styles. Please check the new structure for the [home.md](https://raw.githubusercontent.com/sustainable-software-sustainability/sustainable-software-sustainability.github.io/new-web/content/home.md) file.

This approach covers implicitly the purpose of a general component.
